import Product from "../models/productModel.js"

const seedProducts = [
    // Mobil Telefonlar - Apple iPhone
    {
        name: "iPhone 15 Pro Max 256GB",
        price: 2499.99,
        categoryId: 10101,
        images: ["/images/iphone15promax1.jpg", "/images/iphone15promax2.jpg"],
        description: "Apple iPhone 15 Pro Max 256GB yaddaş ilə. A17 Pro çip, 48MP kamera sistemi və titanyum dizayn.",
        credit_available: true,
        features: {
            brand: "Apple",
            model: "iPhone 15 Pro Max",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.7"',
            camera: "48MP",
            battery: "4441mAh",
            color: "Natural Titanium",
            operating_system: "iOS 17",
        },
    },
    {
        name: "iPhone 14 128GB",
        price: 1899.99,
        categoryId: 10101,
        images: ["/images/iphone14_1.jpg", "/images/iphone14_2.jpg"],
        description: "Apple iPhone 14 128GB yaddaş ilə. A15 Bionic çip və təkmilləşdirilmiş kamera sistemi.",
        credit_available: true,
        features: {
            brand: "Apple",
            model: "iPhone 14",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.1"',
            camera: "12MP",
            battery: "3279mAh",
            color: "Blue",
            operating_system: "iOS 16",
        },
    },

    // Mobil Telefonlar - Samsung
    {
        name: "Samsung Galaxy S24 Ultra 512GB",
        price: 2299.99,
        categoryId: 10102,
        images: ["/images/s24ultra1.jpg", "/images/s24ultra2.jpg"],
        description: "Samsung Galaxy S24 Ultra 512GB. Snapdragon 8 Gen 3, 200MP kamera və S Pen dəstəyi.",
        credit_available: true,
        features: {
            brand: "Samsung",
            model: "Galaxy S24 Ultra",
            storage: "512GB",
            ram: "12GB",
            screen_size: '6.8"',
            camera: "200MP",
            battery: "5000mAh",
            color: "Titanium Gray",
            operating_system: "Android 14",
        },
    },
    {
        name: "Samsung Galaxy A54 256GB",
        price: 899.99,
        categoryId: 10102,
        images: ["/images/galaxya54_1.jpg", "/images/galaxya54_2.jpg"],
        description: "Samsung Galaxy A54 256GB. Exynos 1380 prosessor və 50MP kamera sistemi.",
        credit_available: true,
        features: {
            brand: "Samsung",
            model: "Galaxy A54",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.4"',
            camera: "50MP",
            battery: "5000mAh",
            color: "Awesome Violet",
            operating_system: "Android 13",
        },
    },
    {
        name: "Samsung Galaxy S24 Ultra 512GB",
        price: 2299.99,
        categoryId: 10102,
        images: ["/images/s24ultra1.jpg", "/images/s24ultra2.jpg"],
        description: "Samsung Galaxy S24 Ultra 512GB. Snapdragon 8 Gen 3, 200MP kamera və S Pen dəstəyi.",
        credit_available: true,
        features: {
            brand: "Samsung",
            model: "Galaxy S24 Ultra",
            storage: "512GB",
            ram: "12GB",
            screen_size: '6.8"',
            camera: "200MP",
            battery: "5000mAh",
            color: "Titanium Gray",
            operating_system: "Android 14",
        },
    },
    {
        name: "Samsung Galaxy A54 256GB",
        price: 899.99,
        categoryId: 10102,
        images: ["/images/galaxya54_1.jpg", "/images/galaxya54_2.jpg"],
        description: "Samsung Galaxy A54 256GB. Exynos 1380 prosessor və 50MP kamera sistemi.",
        credit_available: true,
        features: {
            brand: "Samsung",
            model: "Galaxy A54",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.4"',
            camera: "50MP",
            battery: "5000mAh",
            color: "Awesome Violet",
            operating_system: "Android 13",
        },
    },
    {
        name: "Samsung Galaxy S23 FE 128GB",
        price: 1099.99,
        categoryId: 10102,
        images: ["/images/s23fe1.jpg", "/images/s23fe2.jpg"],
        description: "Samsung Galaxy S23 FE 128GB. Snapdragon 4 Gen 1, 50MP üçlü kamera sistemi.",
        credit_available: true,
        features: {
            brand: "Samsung",
            model: "Galaxy S23 FE",
            storage: "128GB",
            ram: "8GB",
            screen_size: '6.4"',
            camera: "50MP",
            battery: "4500mAh",
            color: "Graphite",
            operating_system: "Android 13",
        },
    },
    {
        name: "Samsung Galaxy Z Fold5 512GB",
        price: 3499.99,
        categoryId: 10102,
        images: ["/images/galaxyfold5_1.jpg", "/images/galaxyfold5_2.jpg"],
        description: "Samsung Galaxy Z Fold5 512GB. Snapdragon 8 Gen 2, qatlanan ekran və yenilənmiş dizayn.",
        credit_available: false,
        features: {
            brand: "Samsung",
            model: "Galaxy Z Fold5",
            storage: "512GB",
            ram: "12GB",
            screen_size: '7.6" (main), 6.2" (cover)',
            camera: "50MP üçlü kamera",
            battery: "4400mAh",
            color: "Phantom Black",
            operating_system: "Android 13",
        },
    },
    {
        name: "Samsung Galaxy A14 64GB",
        price: 499.99,
        categoryId: 10102,
        images: ["/images/galaxya14_1.jpg", "/images/galaxya14_2.jpg"],
        description: "Samsung Galaxy A14 64GB. MediaTek Helio G80, 50MP kamera və uzun batareya ömrü.",
        credit_available: true,
        features: {
            brand: "Samsung",
            model: "Galaxy A14",
            storage: "64GB",
            ram: "4GB",
            screen_size: '6.6"',
            camera: "50MP",
            battery: "5000mAh",
            color: "Light Green",
            operating_system: "Android 13",
        },
    },
    {
        name: "Samsung Galaxy S23 256GB",
        price: 1999.99,
        categoryId: 10102,
        images: ["/images/s23_1.jpg", "/images/s23_2.jpg"],
        description: "Samsung Galaxy S23 256GB. Snapdragon 8 Gen 2, 50MP kamera və kompakt dizayn.",
        credit_available: false,
        features: {
            brand: "Samsung",
            model: "Galaxy S23",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.1"',
            camera: "50MP",
            battery: "3900mAh",
            color: "Cream",
            operating_system: "Android 13",
        },
    },

    // Mobil Telefonlar - Xiaomi
    {
        name: "Xiaomi 13 Pro 256GB",
        price: 1599.99,
        categoryId: 10103,
        images: ["/images/xiaomi13pro1.jpg", "/images/xiaomi13pro2.jpg"],
        description: "Xiaomi 13 Pro 256GB. Snapdragon 8 Gen 2 və Leica kamera sistemi.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "13 Pro",
            storage: "256GB",
            ram: "12GB",
            screen_size: '6.73"',
            camera: "50MP",
            battery: "4820mAh",
            color: "Ceramic Black",
            operating_system: "MIUI 14",
        },
    },
    // Mobil Telefonlar - Xiaomi
    {
        name: "Xiaomi 13 Pro 256GB",
        price: 1599.99,
        categoryId: 10103,
        images: ["/images/xiaomi13pro1.jpg", "/images/xiaomi13pro2.jpg"],
        description: "Xiaomi 13 Pro 256GB. Snapdragon 8 Gen 2 və Leica kamera sistemi.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "13 Pro",
            storage: "256GB",
            ram: "12GB",
            screen_size: '6.73"',
            camera: "50MP",
            battery: "4820mAh",
            color: "Ceramic Black",
            operating_system: "MIUI 14",
        },
    },
    {
        name: "Xiaomi 13 128GB",
        price: 1299.99,
        categoryId: 10103,
        images: ["/images/xiaomi13_1.jpg", "/images/xiaomi13_2.jpg"],
        description: "Xiaomi 13 128GB. Snapdragon 8 Gen 2, kompakt və güclü performans.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "13",
            storage: "128GB",
            ram: "8GB",
            screen_size: '6.36"',
            camera: "50MP",
            battery: "4500mAh",
            color: "Green",
            operating_system: "MIUI 14",
        },
    },
    {
        name: "Xiaomi Redmi Note 12 Pro+ 256GB",
        price: 699.99,
        categoryId: 10103,
        images: ["/images/redminote12proplus1.jpg", "/images/redminote12proplus2.jpg"],
        description: "Xiaomi Redmi Note 12 Pro+ 256GB. 200MP kamera və MediaTek Dimensity 1080.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 12 Pro+",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.67"',
            camera: "200MP",
            battery: "4500mAh",
            color: "Blue",
            operating_system: "MIUI 14",
        },
    },
    {
        name: "Xiaomi Redmi Note 12 128GB",
        price: 399.99,
        categoryId: 10103,
        images: ["/images/redminote12_1.jpg", "/images/redminote12_2.jpg"],
        description: "Xiaomi Redmi Note 12 128GB. Snapdragon 4 Gen 1 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 12",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "48MP",
            battery: "4500mAh",
            color: "Black",
            operating_system: "MIUI 14",
        },
    },
    {
        name: "Xiaomi Poco F5 Pro 256GB",
        price: 899.99,
        categoryId: 10103,
        images: ["/images/pocof5pro1.jpg", "/images/pocof5pro2.jpg"],
        description: "Xiaomi Poco F5 Pro 256GB. Snapdragon 8+ Gen 1 və 120Hz AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco F5 Pro",
            storage: "256GB",
            ram: "12GB",
            screen_size: '6.67"',
            camera: "64MP",
            battery: "4800mAh",
            color: "Silver",
            operating_system: "MIUI 14",
        },
    },
    {
        name: "Xiaomi Poco X5 Pro 256GB",
        price: 549.99,
        categoryId: 10103,
        images: ["/images/pocox5pro1.jpg", "/images/pocox5pro2.jpg"],
        description: "Xiaomi Poco X5 Pro 256GB. Snapdragon 778G ve AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco X5 Pro",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "5000mAh",
            color: "Black",
            operating_system: "MIUI 14",
        },
    },
    {
        name: "Xiaomi Redmi 12C 64GB",
        price: 199.99,
        categoryId: 10103,
        images: ["/images/redmi12c1.jpg", "/images/redmi12c2.jpg"],
        description: "Xiaomi Redmi 12C 64GB. MediaTek Helio G85 və böyük batareya.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi 12C",
            storage: "64GB",
            ram: "4GB",
            screen_size: '6.71"',
            camera: "50MP",
            battery: "5000mAh",
            color: "Midnight Black",
            operating_system: "MIUI 14",
        },
    },
    {
        name: "Xiaomi Redmi Note 11 Pro 128GB",
        price: 499.99,
        categoryId: 10103,
        images: ["/images/redminote11pro1.jpg", "/images/redminote11pro2.jpg"],
        description: "Xiaomi Redmi Note 11 Pro 128GB. AMOLED ekran və 108MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 11 Pro",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "4500mAh",
            color: "Blue",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi 12T Pro 256GB",
        price: 799.99,
        categoryId: 10103,
        images: ["/images/12tpro1.jpg", "/images/12tpro2.jpg"],
        description: "Xiaomi 12T Pro 256GB. Snapdragon 8+ Gen 1 və 200MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "12T Pro",
            storage: "256GB",
            ram: "12GB",
            screen_size: '6.67"',
            camera: "200MP",
            battery: "5000mAh",
            color: "Gray",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi 12X 128GB",
        price: 599.99,
        categoryId: 10103,
        images: ["/images/12x1.jpg", "/images/12x2.jpg"],
        description: "Xiaomi 12X 128GB. Snapdragon 870 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "12X",
            storage: "128GB",
            ram: "8GB",
            screen_size: '6.28"',
            camera: "50MP",
            battery: "4500mAh",
            color: "Black",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi Note 10 Pro 128GB",
        price: 399.99,
        categoryId: 10103,
        images: ["/images/redminote10pro1.jpg", "/images/redminote10pro2.jpg"],
        description: "Xiaomi Redmi Note 10 Pro 128GB. AMOLED ekran və 108MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 10 Pro",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "5020mAh",
            color: "Gradient Bronze",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Poco M5 Pro 128GB",
        price: 299.99,
        categoryId: 10103,
        images: ["/images/pocom5pro1.jpg", "/images/pocom5pro2.jpg"],
        description: "Xiaomi Poco M5 Pro 128GB. MediaTek Dimensity 920 və 90Hz ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco M5 Pro",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "48MP",
            battery: "5000mAh",
            color: "Black",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi Note 11 64GB",
        price: 249.99,
        categoryId: 10103,
        images: ["/images/redminote11_1.jpg", "/images/redminote11_2.jpg"],
        description: "Xiaomi Redmi Note 11 64GB. Snapdragon 680 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 11",
            storage: "64GB",
            ram: "4GB",
            screen_size: '6.43"',
            camera: "50MP",
            battery: "5000mAh",
            color: "Blue",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Mi Mix Fold 2 512GB",
        price: 2499.99,
        categoryId: 10103,
        images: ["/images/mimixfold21.jpg", "/images/mimixfold22.jpg"],
        description: "Xiaomi Mi Mix Fold 2 512GB. Qatlana bilən ekran və Snapdragon 8+ Gen 1.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Mi Mix Fold 2",
            storage: "512GB",
            ram: "12GB",
            screen_size: '8.02"',
            camera: "50MP",
            battery: "4500mAh",
            color: "Black",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi 10C 64GB",
        price: 179.99,
        categoryId: 10103,
        images: ["/images/redmi10c1.jpg", "/images/redmi10c2.jpg"],
        description: "Xiaomi Redmi 10C 64GB. MediaTek Helio G88 və böyük batareya.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi 10C",
            storage: "64GB",
            ram: "4GB",
            screen_size: '6.71"',
            camera: "50MP",
            battery: "5000mAh",
            color: "Graphite Gray",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Poco X4 Pro 128GB",
        price: 449.99,
        categoryId: 10103,
        images: ["/images/pocox4pro1.jpg", "/images/pocox4pro2.jpg"],
        description: "Xiaomi Poco X4 Pro 128GB. Snapdragon 695 və 120Hz AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco X4 Pro",
            storage: "128GB",
            ram: "8GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "4500mAh",
            color: "Yellow",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi Note 8 64GB",
        price: 179.99,
        categoryId: 10103,
        images: ["/images/redminote8_1.jpg", "/images/redminote8_2.jpg"],
        description: "Xiaomi Redmi Note 8 64GB. Snapdragon 665 və 48MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 8",
            storage: "64GB",
            ram: "4GB",
            screen_size: '6.3"',
            camera: "48MP",
            battery: "4000mAh",
            color: "Neptune Blue",
            operating_system: "MIUI 11",
        },
    },
    {
        name: "Xiaomi Redmi 9C 32GB",
        price: 109.99,
        categoryId: 10103,
        images: ["/images/redmi9c1.jpg", "/images/redmi9c2.jpg"],
        description: "Xiaomi Redmi 9C 32GB. MediaTek Helio G35 və böyük batareya.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi 9C",
            storage: "32GB",
            ram: "3GB",
            screen_size: '6.53"',
            camera: "13MP",
            battery: "5000mAh",
            color: "Sunset Blue",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Mi 11 Lite 128GB",
        price: 399.99,
        categoryId: 10103,
        images: ["/images/mi11lite1.jpg", "/images/mi11lite2.jpg"],
        description: "Xiaomi Mi 11 Lite 128GB. Snapdragon 732G və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Mi 11 Lite",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.55"',
            camera: "64MP",
            battery: "4250mAh",
            color: "Truffle Black",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Redmi Note 9 Pro 128GB",
        price: 299.99,
        categoryId: 10103,
        images: ["/images/redminote9pro1.jpg", "/images/redminote9pro2.jpg"],
        description: "Xiaomi Redmi Note 9 Pro 128GB. Snapdragon 720G və 64MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 9 Pro",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "64MP",
            battery: "5020mAh",
            color: "Glacier White",
            operating_system: "MIUI 11",
        },
    },
    {
        name: "Xiaomi Redmi 8A 32GB",
        price: 99.99,
        categoryId: 10103,
        images: ["/images/redmi8a1.jpg", "/images/redmi8a2.jpg"],
        description: "Xiaomi Redmi 8A 32GB. Snapdragon 439 və böyük batareya.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi 8A",
            storage: "32GB",
            ram: "2GB",
            screen_size: '6.22"',
            camera: "12MP",
            battery: "5000mAh",
            color: "Midnight Black",
            operating_system: "MIUI 11",
        },
    },
    {
        name: "Xiaomi Redmi K50 Gaming 256GB",
        price: 799.99,
        categoryId: 10103,
        images: ["/images/redmik50gaming1.jpg", "/images/redmik50gaming2.jpg"],
        description: "Xiaomi Redmi K50 Gaming 256GB. MediaTek Dimensity 8100+ və 120Hz ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi K50 Gaming",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.67"',
            camera: "64MP",
            battery: "5065mAh",
            color: "Black",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Mi 10T Pro 256GB",
        price: 649.99,
        categoryId: 10103,
        images: ["/images/mi10tpro1.jpg", "/images/mi10tpro2.jpg"],
        description: "Xiaomi Mi 10T Pro 256GB. Snapdragon 865 və 108MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Mi 10T Pro",
            storage: "256GB",
            ram: "8GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "5000mAh",
            color: "Lunar Silver",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Redmi Note 7 64GB",
        price: 149.99,
        categoryId: 10103,
        images: ["/images/redminote7_1.jpg", "/images/redminote7_2.jpg"],
        description: "Xiaomi Redmi Note 7 64GB. Snapdragon 660 və 48MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 7",
            storage: "64GB",
            ram: "4GB",
            screen_size: '6.3"',
            camera: "48MP",
            battery: "4000mAh",
            color: "Neptune Blue",
            operating_system: "MIUI 10",
        },
    },
    {
        name: "Xiaomi Poco F4 GT 256GB",
        price: 899.99,
        categoryId: 10103,
        images: ["/images/pocof4gt1.jpg", "/images/pocof4gt2.jpg"],
        description: "Xiaomi Poco F4 GT 256GB. Snapdragon 8 Gen 1 və 120Hz AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco F4 GT",
            storage: "256GB",
            ram: "12GB",
            screen_size: '6.67"',
            camera: "64MP",
            battery: "4700mAh",
            color: "Black",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi Note 11S 128GB",
        price: 349.99,
        categoryId: 10103,
        images: ["/images/redminote11s1.jpg", "/images/redminote11s2.jpg"],
        description: "Xiaomi Redmi Note 11S 128GB. MediaTek Helio G96 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 11S",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.43"',
            camera: "108MP",
            battery: "4500mAh",
            color: "Graphite Gray",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi 9T 64GB",
        price: 179.99,
        categoryId: 10103,
        images: ["/images/redmi9t1.jpg", "/images/redmi9t2.jpg"],
        description: "Xiaomi Redmi 9T 64GB. Snapdragon 662 və böyük batareya.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi 9T",
            storage: "64GB",
            ram: "4GB",
            screen_size: '6.53"',
            camera: "48MP",
            battery: "6000mAh",
            color: "Carbon Gray",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Mi 9T Pro 128GB",
        price: 399.99,
        categoryId: 10103,
        images: ["/images/mi9tpro1.jpg", "/images/mi9tpro2.jpg"],
        description: "Xiaomi Mi 9T Pro 128GB. Snapdragon 855 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Mi 9T Pro",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.39"',
            camera: "48MP",
            battery: "4000mAh",
            color: "Glacier Blue",
            operating_system: "MIUI 11",
        },
    },
    {
        name: "Xiaomi Redmi Note 10 Pro 128GB",
        price: 399.99,
        categoryId: 10103,
        images: ["/images/redminote10pro1.jpg", "/images/redminote10pro2.jpg"],
        description: "Xiaomi Redmi Note 10 Pro 128GB. Snapdragon 732G və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 10 Pro",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "5020mAh",
            color: "Gradient Bronze",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Poco M4 Pro 5G 128GB",
        price: 269.99,
        categoryId: 10103,
        images: ["/images/pocom4pro5g1.jpg", "/images/pocom4pro5g2.jpg"],
        description: "Xiaomi Poco M4 Pro 5G 128GB. MediaTek Helio G96 və 90Hz ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco M4 Pro 5G",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.43"',
            camera: "64MP",
            battery: "5000mAh",
            color: "Cool Blue",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi Note 5 64GB",
        price: 139.99,
        categoryId: 10103,
        images: ["/images/redminote5_1.jpg", "/images/redminote5_2.jpg"],
        description: "Xiaomi Redmi Note 5 64GB. Snapdragon 636 və 12MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 5",
            storage: "64GB",
            ram: "4GB",
            screen_size: '5.99"',
            camera: "12MP",
            battery: "4000mAh",
            color: "Black",
            operating_system: "MIUI 10",
        },
    },
    {
        name: "Xiaomi Redmi Note 4X 64GB",
        price: 119.99,
        categoryId: 10103,
        images: ["/images/redminote4x1.jpg", "/images/redminote4x2.jpg"],
        description: "Xiaomi Redmi Note 4X 64GB. Snapdragon 625 və 13MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 4X",
            storage: "64GB",
            ram: "4GB",
            screen_size: '5.5"',
            camera: "13MP",
            battery: "4100mAh",
            color: "Gold",
            operating_system: "MIUI 10",
        },
    },
    {
        name: "Xiaomi Redmi 7 32GB",
        price: 109.99,
        categoryId: 10103,
        images: ["/images/redmi7_1.jpg", "/images/redmi7_2.jpg"],
        description: "Xiaomi Redmi 7 32GB. Snapdragon 632 və 12MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi 7",
            storage: "32GB",
            ram: "3GB",
            screen_size: '6.26"',
            camera: "12MP",
            battery: "4000mAh",
            color: "Blue",
            operating_system: "MIUI 10",
        },
    },
    {
        name: "Xiaomi Poco X3 Pro 128GB",
        price: 299.99,
        categoryId: 10103,
        images: ["/images/pocox3pro1.jpg", "/images/pocox3pro2.jpg"],
        description: "Xiaomi Poco X3 Pro 128GB. Snapdragon 860 və 120Hz ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco X3 Pro",
            storage: "128GB",
            ram: "8GB",
            screen_size: '6.67"',
            camera: "48MP",
            battery: "5160mAh",
            color: "Shadow Black",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Mi Mix 4 512GB",
        price: 1299.99,
        categoryId: 10103,
        images: ["/images/mimix41.jpg", "/images/mimix42.jpg"],
        description: "Xiaomi Mi Mix 4 512GB. Snapdragon 888 və 108MP kamera.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Mi Mix 4",
            storage: "512GB",
            ram: "12GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "4500mAh",
            color: "White",
            operating_system: "MIUI 12",
        },
    },
    {
        name: "Xiaomi Redmi Note 12 128GB",
        price: 399.99,
        categoryId: 10103,
        images: ["/images/redminote12_1.jpg", "/images/redminote12_2.jpg"],
        description: "Xiaomi Redmi Note 12 128GB. Snapdragon 4 Gen 1 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 12",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "48MP",
            battery: "4500mAh",
            color: "Black",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Redmi Note 11 Pro 128GB",
        price: 449.99,
        categoryId: 10103,
        images: ["/images/redminote11pro1.jpg", "/images/redminote11pro2.jpg"],
        description: "Xiaomi Redmi Note 11 Pro 128GB. MediaTek Helio G96 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Redmi Note 11 Pro",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "108MP",
            battery: "4500mAh",
            color: "Graphite Gray",
            operating_system: "MIUI 13",
        },
    },
    {
        name: "Xiaomi Poco F3 128GB",
        price: 399.99,
        categoryId: 10103,
        images: ["/images/pocof31.jpg", "/images/pocof32.jpg"],
        description: "Xiaomi Poco F3 128GB. Snapdragon 870 və AMOLED ekran.",
        credit_available: true,
        features: {
            brand: "Xiaomi",
            model: "Poco F3",
            storage: "128GB",
            ram: "6GB",
            screen_size: '6.67"',
            camera: "48MP",
            battery: "4520mAh",
            color: "Night Black",
            operating_system: "MIUI 12",
        },
    },

    // Smart Saatlar
    {
        name: "Apple Watch Series 9 45mm",
        price: 899.99,
        categoryId: 102,
        images: ["/images/applewatch9_1.jpg", "/images/applewatch9_2.jpg"],
        description: "Apple Watch Series 9 45mm. S9 çip, Always-On Retina ekran və sağlamlıq monitorinqi.",
        credit_available: true,
        features: {
            brand: "Apple",
            model: "Watch Series 9",
            case_size: "45mm",
            display: "Always-On Retina",
            battery_life: "18 saat",
            water_resistance: "50m",
            connectivity: "GPS + Cellular",
            color: "Midnight",
        },
    },
    {
        name: "Samsung Galaxy Watch6 44mm",
        price: 649.99,
        categoryId: 102,
        images: ["/images/galaxywatch6_1.jpg", "/images/galaxywatch6_2.jpg"],
        description: "Samsung Galaxy Watch6 44mm. Exynos W930 çip və təkmilləşdirilmiş sağlamlıq sensoru.",
        credit_available: true,
        features: {
            brand: "Samsung",
            model: "Galaxy Watch6",
            case_size: "44mm",
            display: "Super AMOLED",
            battery_life: "40 saat",
            water_resistance: "5ATM",
            connectivity: "Bluetooth",
            color: "Graphite",
        },
    },

    // Noutbuklar - Apple MacBook
    {
        name: 'MacBook Pro 14" M3 Pro 512GB',
        price: 4299.99,
        categoryId: 20202,
        images: ["/images/macbookpro14_1.jpg", "/images/macbookpro14_2.jpg"],
        description: 'MacBook Pro 14" M3 Pro çip ilə. 512GB SSD və 18GB birləşmiş yaddaş.',
        credit_available: true,
        features: {
            brand: "Apple",
            model: 'MacBook Pro 14"',
            processor: "M3 Pro",
            ram: "18GB",
            storage: "512GB SSD",
            screen_size: '14.2"',
            graphics: "M3 Pro GPU",
            battery_life: "18 saat",
            color: "Space Black",
            operating_system: "macOS Sonoma",
        },
    },
    {
        name: 'MacBook Air 13" M2 256GB',
        price: 2799.99,
        categoryId: 20202,
        images: ["/images/macbookair13_1.jpg", "/images/macbookair13_2.jpg"],
        description: 'MacBook Air 13" M2 çip ilə. 256GB SSD və 8GB birləşmiş yaddaş.',
        credit_available: true,
        features: {
            brand: "Apple",
            model: 'MacBook Air 13"',
            processor: "M2",
            ram: "8GB",
            storage: "256GB SSD",
            screen_size: '13.6"',
            graphics: "M2 GPU",
            battery_life: "18 saat",
            color: "Midnight",
            operating_system: "macOS Ventura",
        },
    },

    // Noutbuklar - HP
    {
        name: "HP Pavilion 15-eh3001nt",
        price: 1899.99,
        categoryId: 20201,
        images: ["/images/hp_pavilion15_1.jpg", "/images/hp_pavilion15_2.jpg"],
        description: 'HP Pavilion 15.6" AMD Ryzen 7 prosessor və 16GB RAM ilə.',
        credit_available: true,
        features: {
            brand: "HP",
            model: "Pavilion 15-eh3001nt",
            processor: "AMD Ryzen 7 5825U",
            ram: "16GB",
            storage: "512GB SSD",
            screen_size: '15.6"',
            graphics: "AMD Radeon",
            battery_life: "8 saat",
            color: "Natural Silver",
            operating_system: "Windows 11",
        },
    },
    {
        name: "Dell XPS 13 9310",
        price: 2299.99,
        categoryId: 20201,
        images: ["/images/dell_xps13_1.jpg", "/images/dell_xps13_2.jpg"],
        description: 'Dell XPS 13 13.4" Intel Core i7, 16GB RAM və 512GB SSD ilə.',
        credit_available: false,
        features: {
            brand: "Dell",
            model: "XPS 13 9310",
            processor: "Intel Core i7-1185G7",
            ram: "16GB",
            storage: "512GB SSD",
            screen_size: '13.4"',
            graphics: "Intel Iris Xe",
            battery_life: "12 saat",
            color: "Silver",
            operating_system: "Windows 11",
        },
    },
    {
        name: "Apple MacBook Air M2",
        price: 2799.99,
        categoryId: 20201,
        images: ["/images/macbook_air_m2_1.jpg", "/images/macbook_air_m2_2.jpg"],
        description: 'Apple MacBook Air 13.6" M2 çip, 8GB RAM və 256GB SSD ilə.',
        credit_available: false,
        features: {
            brand: "Apple",
            model: "MacBook Air M2",
            processor: "Apple M2",
            ram: "8GB",
            storage: "256GB SSD",
            screen_size: '13.6"',
            graphics: "Apple GPU",
            battery_life: "18 saat",
            color: "Space Gray",
            operating_system: "macOS Ventura",
        },
    },
    {
        name: "Lenovo Legion 5 15ACH6",
        price: 1999.99,
        categoryId: 20201,
        images: ["/images/lenovo_legion5_1.jpg", "/images/lenovo_legion5_2.jpg"],
        description: 'Lenovo Legion 5 15.6" AMD Ryzen 7 5800H və NVIDIA RTX 3060 ilə.',
        credit_available: true,
        features: {
            brand: "Lenovo",
            model: "Legion 5 15ACH6",
            processor: "AMD Ryzen 7 5800H",
            ram: "16GB",
            storage: "512GB SSD",
            screen_size: '15.6"',
            graphics: "NVIDIA GeForce RTX 3060",
            battery_life: "7 saat",
            color: "Phantom Black",
            operating_system: "Windows 11",
        },
    },
    {
        name: "ASUS ROG Zephyrus G14",
        price: 2499.99,
        categoryId: 20201,
        images: ["/images/asus_rog_g14_1.jpg", "/images/asus_rog_g14_2.jpg"],
        description: 'ASUS ROG Zephyrus G14 14" AMD Ryzen 9, 16GB RAM və 1TB SSD ilə.',
        credit_available: false,
        features: {
            brand: "ASUS",
            model: "ROG Zephyrus G14",
            processor: "AMD Ryzen 9 5900HS",
            ram: "16GB",
            storage: "1TB SSD",
            screen_size: '14"',
            graphics: "NVIDIA GeForce RTX 3060",
            battery_life: "10 saat",
            color: "Moonlight White",
            operating_system: "Windows 11",
        },
    },
    {
        name: "Microsoft Surface Laptop 5",
        price: 2199.99,
        categoryId: 20201,
        images: ["/images/surface_laptop5_1.jpg", "/images/surface_laptop5_2.jpg"],
        description: 'Microsoft Surface Laptop 5 13.5" Intel Core i7, 16GB RAM və 512GB SSD.',
        credit_available: false,
        features: {
            brand: "Microsoft",
            model: "Surface Laptop 5",
            processor: "Intel Core i7-1255U",
            ram: "16GB",
            storage: "512GB SSD",
            screen_size: '13.5"',
            graphics: "Intel Iris Xe",
            battery_life: "17 saat",
            color: "Platinum",
            operating_system: "Windows 11",
        },
    },
    {
        name: "Acer Swift 3",
        price: 1299.99,
        categoryId: 20201,
        images: ["/images/acer_swift3_1.jpg", "/images/acer_swift3_2.jpg"],
        description: 'Acer Swift 3 14" AMD Ryzen 5, 8GB RAM və 256GB SSD ilə.',
        credit_available: true,
        features: {
            brand: "Acer",
            model: "Swift 3",
            processor: "AMD Ryzen 5 5500U",
            ram: "8GB",
            storage: "256GB SSD",
            screen_size: '14"',
            graphics: "AMD Radeon Graphics",
            battery_life: "11 saat",
            color: "Silver",
            operating_system: "Windows 11",
        },
    },
    {
        name: "HP EliteBook 840 G8",
        price: 2399.99,
        categoryId: 20201,
        images: ["/images/hp_elitebook_840_1.jpg", "/images/hp_elitebook_840_2.jpg"],
        description: 'HP EliteBook 840 G8 14" Intel Core i7, 16GB RAM və 512GB SSD ilə.',
        credit_available: false,
        features: {
            brand: "HP",
            model: "EliteBook 840 G8",
            processor: "Intel Core i7-1165G7",
            ram: "16GB",
            storage: "512GB SSD",
            screen_size: '14"',
            graphics: "Intel Iris Xe",
            battery_life: "10 saat",
            color: "Silver",
            operating_system: "Windows 11 Pro",
        },
    },
    {
        name: "Dell Inspiron 15 5000",
        price: 1599.99,
        categoryId: 20201,
        images: ["/images/dell_inspiron15_1.jpg", "/images/dell_inspiron15_2.jpg"],
        description: 'Dell Inspiron 15 15.6" Intel Core i5, 8GB RAM və 256GB SSD ilə.',
        credit_available: true,
        features: {
            brand: "Dell",
            model: "Inspiron 15 5000",
            processor: "Intel Core i5-1135G7",
            ram: "8GB",
            storage: "256GB SSD",
            screen_size: '15.6"',
            graphics: "Intel Iris Xe",
            battery_life: "9 saat",
            color: "Black",
            operating_system: "Windows 11",
        },
    },

    // Planşetler - Apple iPad
    {
        name: 'iPad Pro 12.9" M2 256GB',
        price: 2499.99,
        categoryId: 20301,
        images: ["/images/ipadpro129_1.jpg", "/images/ipadpro129_2.jpg"],
        description: 'iPad Pro 12.9" M2 çip ilə. 256GB yaddaş və Apple Pencil dəstəyi.',
        credit_available: true,
        features: {
            brand: "Apple",
            model: 'iPad Pro 12.9"',
            processor: "M2",
            ram: "8GB",
            storage: "256GB",
            screen_size: '12.9"',
            camera: "12MP",
            battery_life: "10 saat",
            color: "Space Gray",
            operating_system: "iPadOS 16",
        },
    },
    {
        name: 'iPad Air 10.9" 64GB',
        price: 1299.99,
        categoryId: 20301,
        images: ["/images/ipadair_1.jpg", "/images/ipadair_2.jpg"],
        description: 'iPad Air 10.9" A14 Bionic çip ilə. 64GB yaddaş və Touch ID.',
        credit_available: true,
        features: {
            brand: "Apple",
            model: 'iPad Air 10.9"',
            processor: "A14 Bionic",
            ram: "4GB",
            storage: "64GB",
            screen_size: '10.9"',
            camera: "12MP",
            battery_life: "10 saat",
            color: "Sky Blue",
            operating_system: "iPadOS 15",
        },
    },

    // Qulaqcıqlar
    {
        name: "Apple AirPods Pro 2nd Gen",
        price: 599.99,
        categoryId: 301,
        images: ["/images/airpodspro2_1.jpg", "/images/airpodspro2_2.jpg"],
        description: "Apple AirPods Pro 2-ci nəsil. Aktiv səs-küy ləğvi və məkan səsi.",
        credit_available: true,
        features: {
            brand: "Apple",
            model: "AirPods Pro 2nd Gen",
            type: "In-ear",
            noise_cancellation: "Active",
            battery_life: "6 saat (30 saat case ilə)",
            connectivity: "Bluetooth 5.3",
            water_resistance: "IPX4",
            color: "White",
        },
    },
    {
        name: "Sony WH-1000XM5",
        price: 799.99,
        categoryId: 301,
        images: ["/images/sony_wh1000xm5_1.jpg", "/images/sony_wh1000xm5_2.jpg"],
        description: "Sony WH-1000XM5 simsiz qulaqcıqlar. Ən yaxşı səs-küy ləğvi texnologiyası.",
        credit_available: true,
        features: {
            brand: "Sony",
            model: "WH-1000XM5",
            type: "Over-ear",
            noise_cancellation: "Industry Leading",
            battery_life: "30 saat",
            connectivity: "Bluetooth 5.2",
            quick_charge: "3 dəq = 3 saat",
            color: "Black",
        },
    },

    // PlayStation konsolları
    {
        name: "Sony PlayStation 5 825GB",
        price: 1299.99,
        categoryId: 407,
        images: ["/images/ps5_1.jpg", "/images/ps5_2.jpg"],
        description: "Sony PlayStation 5 konsolu. 825GB SSD və 4K oyun dəstəyi.",
        credit_available: true,
        features: {
            brand: "Sony",
            model: "PlayStation 5",
            storage: "825GB SSD",
            resolution: "4K",
            processor: "AMD Zen 2",
            graphics: "AMD RDNA 2",
            ram: "16GB GDDR6",
            optical_drive: "Ultra HD Blu-ray",
            color: "White",
        },
    },

    // Xbox konsolları
    {
        name: "Microsoft Xbox Series X 1TB",
        price: 1199.99,
        categoryId: 413,
        images: ["/images/xbox_series_x_1.jpg", "/images/xbox_series_x_2.jpg"],
        description: "Microsoft Xbox Series X konsolu. 1TB SSD və 4K 120fps oyun dəstəyi.",
        credit_available: true,
        features: {
            brand: "Microsoft",
            model: "Xbox Series X",
            storage: "1TB SSD",
            resolution: "4K",
            processor: "AMD Zen 2",
            graphics: "AMD RDNA 2",
            ram: "16GB GDDR6",
            optical_drive: "4K UHD Blu-ray",
            color: "Black",
        },
    },

    // Fotokameralar
    {
        name: "Canon EOS R6 Mark II Body",
        price: 5499.99,
        categoryId: 501,
        images: ["/images/canon_r6_mark2_1.jpg", "/images/canon_r6_mark2_2.jpg"],
        description: "Canon EOS R6 Mark II peşəkar fotokamera. 24.2MP tam kadr sensor.",
        credit_available: true,
        features: {
            brand: "Canon",
            model: "EOS R6 Mark II",
            sensor: "24.2MP Full Frame",
            iso_range: "100-102400",
            video: "4K 60fps",
            image_stabilization: "8-stop IBIS",
            autofocus: "Dual Pixel CMOS AF II",
            battery_life: "760 shots",
            color: "Black",
        },
    },

    // SSD Disklər
    {
        name: "Samsung 980 PRO 1TB NVMe SSD",
        price: 299.99,
        categoryId: 20501,
        images: ["/images/samsung_980pro_1.jpg", "/images/samsung_980pro_2.jpg"],
        description: "Samsung 980 PRO 1TB NVMe M.2 SSD. PCIe 4.0 dəstəyi və yüksək sürət.",
        credit_available: false,
        features: {
            brand: "Samsung",
            model: "980 PRO",
            capacity: "1TB",
            interface: "PCIe 4.0 NVMe M.2",
            read_speed: "7000 MB/s",
            write_speed: "5000 MB/s",
            form_factor: "M.2 2280",
            warranty: "5 il",
        },
    },

    // Videokartlar
    {
        name: "NVIDIA GeForce RTX 4070 Ti",
        price: 1899.99,
        categoryId: 20503,
        images: ["/images/rtx4070ti_1.jpg", "/images/rtx4070ti_2.jpg"],
        description: "NVIDIA GeForce RTX 4070 Ti videokart. 12GB GDDR6X yaddaş və ray tracing.",
        credit_available: true,
        features: {
            brand: "NVIDIA",
            model: "GeForce RTX 4070 Ti",
            memory: "12GB GDDR6X",
            memory_bus: "192-bit",
            base_clock: "2310 MHz",
            boost_clock: "2610 MHz",
            ray_tracing: "Yes",
            dlss: "DLSS 3",
            power_consumption: "285W",
        },
    },

    // Prosessorlar
    {
        name: "AMD Ryzen 9 7900X",
        price: 1199.99,
        categoryId: 20504,
        images: ["/images/ryzen9_7900x_1.jpg", "/images/ryzen9_7900x_2.jpg"],
        description: "AMD Ryzen 9 7900X prosessor. 12 nüvə, 24 thread və 5.6GHz boost.",
        credit_available: true,
        features: {
            brand: "AMD",
            model: "Ryzen 9 7900X",
            cores: "12",
            threads: "24",
            base_clock: "4.7 GHz",
            boost_clock: "5.6 GHz",
            cache: "76MB",
            socket: "AM5",
            tdp: "170W",
        },
    },

    // Powerbank
    {
        name: "Anker PowerCore 26800mAh",
        price: 149.99,
        categoryId: 107,
        images: ["/images/anker_powercore_1.jpg", "/images/anker_powercore_2.jpg"],
        description: "Anker PowerCore 26800mAh powerbank. 3 USB port və sürətli şarj.",
        credit_available: false,
        features: {
            brand: "Anker",
            model: "PowerCore 26800",
            capacity: "26800mAh",
            output_ports: "3 USB-A",
            max_output: "3A",
            input: "Micro USB + USB-C",
            fast_charging: "PowerIQ 2.0",
            weight: "490g",
            color: "Black",
        },
    },
]

const seedProductsData = async () => {
    try {
        console.log("Məhsullar əlavə edilir...");
        console.log('seedProducts.legth', seedProducts.length)
        for (const productData of seedProducts) {
            await Product.create(productData);
        }

        console.log("Bütün məhsullar uğurla əlavə edildi!");
    } catch (error) {
        console.error("Məhsullar əlavə edilərkən xəta:", error);
    }
};

export { seedProductsData };
export default seedProductsData;
