export interface FieldConfig {
    type: 'text' | 'number' | 'dropdown' | 'checkbox' | 'textarea';
    label: string;
    name?: string;
    required?: boolean;
    options?: string[];
}

export const categoryFields: Record<string, FieldConfig[]> = {
    'Mobil telefonlar': [
        {
            type: 'dropdown',
            label: 'Model',
            name: 'model',
            options: [
                'Geri',
                'Huawei',
                'Digər mobil telefonlar',
                'Blackberry',
                'Inoi',
                'Caterpillar',
                'Jiayu',
                'Hoffmann',
                'Honor',
                'Sprint',
                'LG',
                'I‑Mate',
                'Xiaomi',
                'Datawind',
                'Google',
                'Alcatel',
                'ZTE',
                'Sony',
                'Apple iPhone',
                'Vivo',
                'Infinix',
                'Vertu',
                'Poco',
                'Oppo',
                'Nokia',
                'Samsung',
                'OnePlus',
                'Lenovo',
                'Realme',
                'Sagem',
                'Prestigio',
                'Tecno',
                'Fly',
                'HTC',
                'T‑Mobile, MDA',
                'Motorola'
            ]
        },
        {
            type: 'textarea',
            label: 'Rəng',
            name: 'color',
        },
        {
            type: 'dropdown',
            label: 'Operativ yaddaş, RAM (GB)',
            name: 'ram',
            options: [
                '2GB',
                '4GB',
                '6GB',
                '8GB',
                '16GB',
                '32GB',
                '64GB',
                '128GB',
                '256GB',
                '512GB',
                '1TB',
                '2TB'
            ]
        },
        {
            type: 'dropdown',
            label: 'Yaddaş tutumu',
            name: 'storage',
            options: [
                '16GB',
                '32GB',
                '64GB',
                '128GB',
                '256GB',
                '512GB',
                '1TB',
                '2TB'
            ]
        },
        {
            type: 'dropdown',
            label: 'Vəziyyət',
            name: 'condition',
            required: true,
            options: ['Yeni', 'İşlənmiş', 'Sıfır kimi', 'Qutusunda']
        },
        {
            type: 'dropdown',
            label: 'Zəmanət',
            name: 'warranty',
            options: ['Var', 'Yox']
        },
        {
            type: 'dropdown',
            label: 'Əlavə olaraq',
            name: 'additionally',
            options: ['Barmaq izi', 'Kredit', 'Qırıq']
        },
    ],
    'Qulaqcıqlar': [
        {
            type: 'dropdown',
            label: 'Brend',
            name: 'brand',
            options: [
                'Apple',
                'Honor',
                'JBL',
                'Marshall',
                'Samsung',
                'Xiaomi',
                '1More',
                '3Q',
                'A4Tech',
                'AIR MUSIC',
                'Accutone',
                'Acefast',
                'Acer',
                'Acme',
                'Addcom',
                'Adenki',
                'Aec',
                'Aeg',
                'Aftershokz',
                'Aiaiai',
                'Aircoustic',
                'Airon',
                'Aiwa',
                'Akg',
                'Allen&Heath',
                'Alpha Design Labs',
                'Alpine',
                'Altair',
                'American Audio',
                'Anker',
                'Aquapac',
                'Archos',
                'Arctic',
                'Armaggeddon',
                'Art Trend',
                'Astro Gaming',
                'Astrotec',
                'Asus',
                'Atlanfa',
                'Audeze',
                'Audio-Technica',
                'Audio Zenith',
                'Audioquest',
                'Aula',
                'Ausdom',
                'Avalanche',
                'Avantree',
                'Awei',
                'Axelvox',
                'B&W',
                'BYZ',
                'Bang & Olufsen',
                'Baseus',
                'Beats by Dr. Dre',
                'Behringer',
                'Belkin',
                'Beyerdynamic',
                'Bloody',
                'Blue Microphones',
                'Bluedio',
                'Bluetrek',
                'Bmw',
                'Boom',
                'Borofone',
                'Bose',
                'Brainwavz',
                'Brateck',
                'Campfire Audio',
                'Cannice',
                'Canyon',
                'Cardas',
                'Cbr',
                'Celebrat',
                'Cellularline',
                'Chord&Major',
                'Clayton',
                'Coloud',
                'Cooler Master',
                'Corsair',
                'Cosonic',
                'Cougar',
                'Cowon',
                'Creative',
                'Cresyn',
                'Crown',
                'Dacom',
                'Dadu',
                'Daimax',
                'Defender',
                'Definitive Technology',
                'Denon',
                'Dita',
                'Dts',
                'Dunu',
                'E-Blue',
                'E-Mu',
                'Earsonics',
                'Easy Touch',
                'Edifier',
                'Elecom',
                'Elephone',
                'Elesound',
                'Emie',
                'Enzatec',
                'Epicgear',
                'Ergo',
                'Esperanza',
                'Etymotic',
                'Extradigital',
                'F&D',
                'Fantech',
                'Fanvil',
                'Fender',
                'Ferrari by Logic3',
                'Fidue',
                'Fiio',
                'Firtech',
                'Fischer Audio',
                'Flc',
                'Florence',
                'Floyd Rose',
                'Flyper',
                'Focal',
                'Fostex',
                'Frends',
                'Fresh N Rebel',
                'G-Cube',
                'G-Star',
                'G.Sound',
                'GMB Audio',
                'Gamdias',
                'Gamemax',
                'Gear4',
                'Gelius',
                'Gembird',
                'Gemini',
                'Gemix',
                'Genius',
                'German Maestro',
                'Golden Field',
                'Golf',
                'Google',
                'Gorsun',
                'Grado',
                'Grand',
                'Greenwave',
                'Gresso',
                'Griffin',
                'Grundig',
                'HBQ',
                'HP',
                'HQ-Tech',
                'HTC',
                'HTR',
                'Hapollo',
                'Happy Plugs',
                'Harman-Kardon',
                'Havit',
                'Hbuds',
                'Hi-Rali',
                'HiFiMan',
                'HiSoundAudio',
                'Hoco',
                'House of Marley',
                'Huawei',
                'HyperX',
                'Icon',
                'Ipipoo',
                'JTS',
                'JVC',
                'Jabees',
                'Jabra',
                'Jam',
                'Jamo',
                'Jaybird',
                'Jays',
                'Jonsen',
                'Joyroom',
                'Just',
                'KEF',
                'KRK',
                'Keeka',
                'Kennerton',
                'Kenwood',
                'King\'s Audio',
                'Kingston',
                'Kitsound',
                'Klipsch',
                'Knowledge Zenith',
                'Koss',
                'Kotion',
                'Krauler',
                'Kruger&Matz',
                'LG',
                'Lapara',
                'Lasmex',
                'Lenovo',
                'Logic',
                'Logicfox',
                'Logitech',
                'M-Audio',
                'MEE audio',
                'MSI',
                'Macally',
                'Mad Catz',
                'Magnat',
                'Mairdi',
                'Manhattan',
                'Marvo',
                'Master & Dynamic',
                'Maxell',
                'Maxxter',
                'Media-Tech',
                'Meizu',
                'Merlin',
                'Meters',
                'Meze',
                'Microlab',
                'Microsoft',
                'Mifo',
                'Mipro',
                'MobiFren',
                'Modecom',
                'Moki',
                'Momax',
                'Monoprice',
                'Monster',
                'Moondrop',
                'Morul',
                'Moshi',
                'Motorola',
                'MrSpeakers',
                'Musical Fidelity',
                'NAD',
                'NRG',
                'Nakamichi',
                'Natec',
                'Noble',
                'Nocs',
                'Nokia',
                'Nomi',
                'Noontec',
                'Nothing',
                'NuForce',
                'Numark',
                'Okean',
                'Onkyo',
                'Onn',
                'Oppo',
                'Oriveti',
                'Ostry',
                'Ovevo',
                'Ovleng',
                'PSB',
                'Padmate',
                'Panasonic',
                'Paradigm',
                'Parrot',
                'Patriot',
                'Pendulumic',
                'Periodic Audio',
                'Phiaton',
                'Philips',
                'Pioneer',
                'Pixus',
                'Plantronics',
                'Polk audio',
                'PreSonus',
                'Pro-Ject',
                'Probass',
                'Prodipe',
                'Proel',
                'PrologiX',
                'Promate',
                'Pryma',
                'Puro',
                'QCY',
                'QKZ',
                'Q Sound',
                'Qitech',
                'RCF',
                'RHA',
                'RS',
                'Radius',
                'Rapoo',
                'Razer',
                'Real-El',
                'Realme',
                'Recrsi',
                'Redragon',
                'Reloop',
                'Remax',
                'Retekess',
                'Rexus',
                'Rhapsodio',
                'Roccat',
                'Rock',
                'Rock Space',
                'Rode',
                'Roland',
                'Roman',
                'Romix',
                'Ryght',
                'SDRD',
                'SMS Audio',
                'Sades',
                'Samson',
                'Satechi',
                'Scosche',
                'Sekaku',
                'Senmai',
                'Sennheiser',
                'Shanling',
                'Sharkoon',
                'Sharp',
                'Shozy',
                'Shure',
                'Sigma mobile',
                'SkullCandy',
                'Smart-Link',
                'Smartfortec',
                'Sol Republic',
                'Somic',
                'Sonorous',
                'Sonus Faber',
                'Sony',
                'Sony Ericsson',
                'Soul',
                'Sound Warrior',
                'Soundmagic',
                'Soundtronix',
                'Speed-Link',
                'Spigen',
                'Stanton',
                'Stax',
                'SteelSeries',
                'Superlux',
                'Supra',
                'Sven',
                'Syllable',
                'T\'Nb',
                'T-Peos',
                'TDK',
                'TFZ',
                'Takstar',
                'Talisman',
                'TaoTronics',
                'Tayogo',
                'Teac',
                'Technics',
                'Tesoro',
                'Thermaltake',
                'Thrustmaster',
                'Toto',
                'Tracer',
                'Treblab',
                'Trinity',
                'Tritton',
                'Tronsmart',
                'Trust',
                'Tt eSPORTS',
                'Turtle Beach',
                'Uiisii',
                'Ultimate Ears',
                'Ultrasone',
                'Urbanears',
                'Urbanista',
                'Usams',
                'Utty',
                'V-Moda',
                'VA audio',
                'VEF',
                'Vava',
                'Venture Electronics',
                'Verico',
                'Vestax',
                'Vinga',
                'Vivanco',
                'WK',
                'Wesdar',
                'Westone',
                'X-Star AST',
                'XO',
                'Xqisit',
                'Yamaha',
                'Ye!!',
                'Yealink',
                'Yison',
                'Yookie',
                'YuLong',
                'Yuin',
                'ZMF',
                'Zalman',
                'Zeus',
                'Zungle',
                'iBasso',
                'iKey Audio',
                'iRiver',
                'xDuoo',
                'Digər brend'
            ]
        },
        {
            type: 'dropdown',
            label: 'Vəziyyəti',
            options: ['Yeni', 'işlənmiş']
        },
        {
            type: 'checkbox',
            label: 'Qoşulma növü',
            options: ['Simli', 'Simsiz']
        }
    ]
}
