export interface FieldConfig {
    type: "text" | "number" | "dropdown" | "checkbox" | "textarea"
    label: string
    name?: string
    required?: boolean
    options?: string[]
}

export const categoryFields: Record<string, FieldConfig[] | null> = {
    "Mobil telefonlar": [
        {
            type: "text",
            label: "Model",
            name: "model",
        },
        {
            type: "textarea",
            label: "Rəng",
            name: "color",
        },
        {
            type: "dropdown",
            label: "Operativ yaddaş, RAM (GB)",
            name: "ram",
            options: ["2GB", "4GB", "6GB", "8GB", "16GB", "32GB"],
        },
        {
            type: "dropdown",
            label: "Yaddaş tutumu",
            name: "storage",
            options: ["16GB", "32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "2TB"],
        },
        {
            type: "dropdown",
            label: "Vəziyyət",
            name: "condition",
            required: true,
            options: ["Yeni", "İşlənmiş", "Sıfır kimi", "Qutusunda"],
        },
        {
            type: "dropdown",
            label: "Zəmanət",
            name: "warranty",
            options: ["Var", "Yox"],
        },
        {
            type: "dropdown",
            label: "Vəziyyəti",
            name: "warranty",
            options: ["Var", "Yox"],
        },
        {
            type: "dropdown",
            label: "Əlavə olaraq",
            name: "additionally",
            options: ["Barmaq izi", "Kredit", "Qırıq"],
        },
    ],
    "Mobil telefonlar üçün digər aksesuarlar": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "SİM-kartlar": [
        { type: "text", label: "Kod*", name: "code", required: true },
        { type: "text", label: "Nömrə*", name: "number", required: true },
        // { type: "text", label: "Vəziyyəti", name: "condition" },
        // { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Smart saatlar": [
        { type: "text", label: "Cins", name: "gender" },
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Funksiyalar", name: "functions" },
        { type: "text", label: "Xüsusiyyətlər", name: "features" },
        { type: "text", label: "Ekran", name: "screen" },
        { type: "text", label: "Daxili yaddaş", name: "internalMemory" },
        { type: "text", label: "Ekran ölçüsü,düym", name: "screenSize" },
        { type: "text", label: "Korpusun materialı", name: "caseMaterial" },
        { type: "text", label: "Rəng", name: "color" },
        // { type: "text", label: "Vəziyyəti", name: "condition" },
        // { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Powerbanklar: [
        { type: "text", label: "Batareyanın həcmi*", name: "capacity", required: true },
        { type: "text", label: "Brend*", name: "brand", required: true },
        // { type: "text", label: "Vəziyyəti", name: "condition" },
        // { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Telefon üçün gamepadlar, triggerlər": null,
    "Telefon üçün stabilizatorlar": null,
    "Smart qolbaqlar": [
        { type: "text", label: "Korpusun materialı", name: "caseMaterial" },
        { type: "text", label: "Ekran", name: "screen" },
        { type: "text", label: "Xüsusiyyətlər", name: "features" },
        { type: "text", label: "Funksiyalar", name: "functions" },
        { type: "text", label: "Cins", name: "gender" },
        // { type: "text", label: "Vəziyyəti", name: "condition" },
        // { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Telefon ehtiyat hissələri": [
        { type: "text", label: "Model*", name: "model", required: true },
        // { type: "text", label: "Vəziyyəti", name: "condition" },
        // { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Selfi çubuqları": null,
    "Video oyunlar və konsollar": null,
    Kabellər: [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Növ*", name: "type", required: true },
        // { type: "text", label: "Vəziyyəti", name: "condition" },
        // { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Modemlər və şəbəkə avadanlıqları": [
        { type: "text", label: "Rəng", name: "color" },
        // { type: "text", label: "Vəziyyəti", name: "condition" },
        // { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Noutbuklar üçün örtük və çantalar": null,
    "Səsgücləndiricilər, qulaqlıqlar и mikrofonlar": null,
    "Flash kartlar": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Yaddaş*", name: "storage", required: true },
        { type: "text", label: "İnterfeys*", name: "interface", required: true },
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Noutbuklar üçün batareyalar": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Digər kompüter aksesuarları": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Dok-stansiya": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Klaviaturalar: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Mauslar: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Foto və videokameralar": [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
    ],
    "Kompüter, noutbuk və planşetlər": [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Nüvələrinin sayı", name: "coreCount" },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Operativ yaddaşı (GB)", name: "ram" },
        { type: "text", label: "Prosessoru", name: "processor" },
        { type: "text", label: "Təyinatı", name: "purpose" },
        { type: "text", label: "Displeyi (düym)", name: "display" },
        { type: "text", label: "Yığıcı növü", name: "assemblyType" },
        { type: "text", label: "Kompüterin növü", name: "computerType" },
        { type: "text", label: "ƏS", name: "os" },
        { type: "text", label: "Videokartı", name: "videoCard" },
        { type: "text", label: "Yaddaş növü", name: "memoryType" },
    ],
    "Noutbuk və netbuklar": [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Nüvələrinin sayı", name: "coreCount" },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Operativ yaddaşı (GB)", name: "ram" },
        { type: "text", label: "Prosessoru", name: "processor" },
        { type: "text", label: "Təyinatı", name: "purpose" },
        { type: "text", label: "Displeyi (düym)", name: "display" },
        { type: "text", label: "Yığıcı növü", name: "assemblyType" },
        { type: "text", label: "Kompüterin növü", name: "computerType" },
        { type: "text", label: "ƏS", name: "os" },
        { type: "text", label: "Videokartı", name: "videoCard" },
        { type: "text", label: "Yaddaş növü", name: "memoryType" },
    ],
    "SSD diskləri": [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Yaddaş", name: "storage" },
        { type: "text", label: "Standart", name: "standard" },
        { type: "text", label: "Növ", name: "type" },
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Kredit", name: "credit" },
    ],
    "Dinamiklər və kolonkalar": [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Kolonka növü*", name: "speakerType", required: true },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Kanalların sayı", name: "channelCount" },
    ],
    "Səs gücləndiriciləri": [
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
    ],
    "Musiqi mərkəzləri": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Maqnitofonlar: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Maqnitofon növü *", name: "tapeRecorderType", required: true },
        { type: "text", label: "Brend", name: "brand" },
    ],
    Diktofonlar: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Brend", name: "brand" },
    ],
    Mikrofonlar: [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Qoşulma növü*", name: "connectionType", required: true },
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
    ],
    "Minidisk və disk pleyerlər": [
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
    ],
    "Digər auditexnika": [
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
    ],
    "iPod və MP3 pleyerlər": [
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
    ],
    Qulaqcıqlar: [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Qoşulma növü*", name: "connectionType", required: true },
        { type: "text", label: "Növü", name: "type" },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Konstruksiyasının növü", name: "constructionType" },
        { type: "text", label: "Təyinatı", name: "purpose" },
    ],
    Radio: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Karaoke: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Videokameralar: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Fotokameralar: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Yaddaş kartları": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Çanta və çexollar": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    İşıqlandırma: [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Enerji qurğuları": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Obyektivlər və filtrləri": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Kabellər və adapterlər": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Digər foto və video aksesuarları": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Videomüşahidə: [
        { type: "text", label: "Brend", name: "brand" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Korpuslar: [
        { type: "text", label: "Brend *", name: "brand", required: true },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Zəmanət", name: "warranty" },
    ],
    "Digər ehtiyat hissələri": [
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Skanerlər: [
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Prosessorlar: [
        { type: "text", label: "Seriya*", name: "series", required: true },
        { type: "text", label: "Model*", name: "model", required: true },
        { type: "text", label: "Tezlik", name: "frequency" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Nüvələrin sayı", name: "coreCount" },
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Kredit", name: "credit" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Qida blokları": [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Güc*", name: "power", required: true },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Videokartlar: [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Qrafik prosessor*", name: "graphicsProcessor", required: true },
        { type: "text", label: "Yaddaş*", name: "memory", required: true },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Kredit", name: "credit" },
    ],
    "Ana platalar": [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Model*", name: "model", required: true },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Printerlər: [
        { type: "text", label: "Vəziyyəti*", name: "condition", required: true },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Elektron kitablar": [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Ekranın diaqonalı (düym)", name: "screenDiagonal" },
        { type: "text", label: "Əlaqə", name: "connection" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Monitorlar: [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Rəng", name: "color" },
        { type: "text", label: "Ekranın diaqonalı (düym)", name: "screenDiagonal" },
        { type: "text", label: "Əlaqə", name: "connection" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Sərt disklər (HDD)": [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Yaddaş*", name: "storage", required: true },
        { type: "text", label: "Standart", name: "standard" },
        { type: "text", label: "Əlaqə", name: "connection" },
        { type: "text", label: "Fırlanma sürəti", name: "rotationSpeed" },
        { type: "text", label: "Kredit", name: "credit" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    Termopasta: [
        { type: "text", label: "Zəmanət", name: "warranty" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
    "Fasiləsiz enerji təchizatı (UPS)": [
        { type: "text", label: "Güc, Vt*", name: "power", required: true },
        { type: "text", label: "Rozetkaların sayı*", name: "socketCount", required: true },
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
    ],
    "Soyutma sistemləri": [
        { type: "text", label: "Brend*", name: "brand", required: true },
        { type: "text", label: "Növ", name: "type" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Zəmanət", name: "warranty" },
    ],
    "Noutbuklar üçün adapterlər": [
        { type: "text", label: "Vəziyyəti", name: "condition" },
        { type: "text", label: "Çatdırılma", name: "delivery" },
    ],
}
